"""Signal Hunter AI — SQLAlchemy 2.x async ORM models and session helpers.

All tables use UUID strings as primary keys (generated by ``uuid.uuid4``).
Timestamps are stored as timezone-naive UTC datetimes; callers should use
``datetime.now(timezone.utc)`` when constructing values.
"""

from __future__ import annotations

import uuid
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from typing import Any, Optional

from sqlalchemy import (
    JSON,
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship
from sqlalchemy.dialects.sqlite import insert as sqlite_insert  # noqa: F401 — re-exported for callers

from signal_hunter.core.config import settings


# ---------------------------------------------------------------------------
# Helper defaults
# ---------------------------------------------------------------------------

def _utcnow() -> datetime:
    """Return the current UTC time as a timezone-naive datetime (SQL-friendly)."""
    return datetime.now(timezone.utc).replace(tzinfo=None)


def _new_uuid() -> str:
    """Return a new UUID4 string suitable for use as a primary key."""
    return str(uuid.uuid4())


# ---------------------------------------------------------------------------
# Declarative base
# ---------------------------------------------------------------------------

class Base(DeclarativeBase):
    """Shared declarative base for all ORM models."""


# ---------------------------------------------------------------------------
# ORM Models
# ---------------------------------------------------------------------------

class UniqueCluster(Base):
    """A de-duplicated cluster of raw items that discuss the same signal/story."""

    __tablename__ = "unique_clusters"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=_new_uuid, comment="UUID4 PK"
    )
    canonical_title: Mapped[str] = mapped_column(
        String(512), nullable=False, comment="Best human-readable title for this cluster."
    )
    category: Mapped[str] = mapped_column(
        String(64), nullable=False, comment="High-level signal category (e.g. 'product_launch')."
    )
    first_seen: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, default=_utcnow,
        comment="UTC timestamp when the earliest member of this cluster was ingested."
    )
    last_seen: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, default=_utcnow, onupdate=_utcnow,
        comment="UTC timestamp of the most recently ingested member."
    )
    source_count: Mapped[int] = mapped_column(
        Integer, nullable=False, default=1,
        comment="Number of distinct sources that have reported this signal."
    )
    sources: Mapped[Optional[Any]] = mapped_column(
        JSON, nullable=True,
        comment="JSON array of source identifiers (e.g. ['reddit', 'hackernews'])."
    )
    embedding_vector: Mapped[Optional[str]] = mapped_column(
        Text, nullable=True,
        comment="JSON-serialised embedding vector used for semantic de-duplication."
    )

    # Relationships
    raw_items: Mapped[list["RawItem"]] = relationship(
        "RawItem", back_populates="cluster", lazy="select"
    )
    classifications: Mapped[list["Classification"]] = relationship(
        "Classification", back_populates="cluster", lazy="select"
    )
    alerts_sent: Mapped[list["AlertSent"]] = relationship(
        "AlertSent", back_populates="cluster", lazy="select"
    )


class RawItem(Base):
    """A single raw item as ingested from any data source before de-duplication."""

    __tablename__ = "raw_items"

    __table_args__ = (
        Index("ix_raw_items_external_id", "external_id"),
        Index("ix_raw_items_source", "source"),
    )

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=_new_uuid, comment="UUID4 PK"
    )
    source: Mapped[str] = mapped_column(
        String(64), nullable=False,
        comment="Ingestion source identifier (e.g. 'reddit', 'youtube')."
    )
    external_id: Mapped[str] = mapped_column(
        String(256), nullable=False,
        comment="Unique identifier as assigned by the originating platform."
    )
    title: Mapped[str] = mapped_column(
        String(512), nullable=False, default="",
        comment="Post/video/article title."
    )
    body: Mapped[Optional[str]] = mapped_column(
        Text, nullable=True,
        comment="Full text body of the item (selftext, description, etc.)."
    )
    url: Mapped[Optional[str]] = mapped_column(
        String(1024), nullable=True,
        comment="Canonical URL of the original item."
    )
    author: Mapped[Optional[str]] = mapped_column(
        String(256), nullable=True,
        comment="Author / channel name on the originating platform."
    )
    fetched_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, default=_utcnow,
        comment="UTC timestamp when the item was fetched by Signal Hunter."
    )
    raw_model_output: Mapped[Optional[str]] = mapped_column(
        Text, nullable=True,
        comment="Raw LLM output produced during any pre-classification step."
    )
    cluster_id: Mapped[Optional[str]] = mapped_column(
        String(36),
        ForeignKey("unique_clusters.id", ondelete="SET NULL"),
        nullable=True,
        comment="FK to the UniqueCluster this item belongs to (set after de-dup)."
    )

    # Relationships
    cluster: Mapped[Optional["UniqueCluster"]] = relationship(
        "UniqueCluster", back_populates="raw_items"
    )


class Classification(Base):
    """The result of running an AI classification pass over a UniqueCluster."""

    __tablename__ = "classifications"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=_new_uuid, comment="UUID4 PK"
    )
    cluster_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("unique_clusters.id", ondelete="CASCADE"),
        nullable=False,
        comment="FK to the cluster that was classified."
    )
    product_name: Mapped[Optional[str]] = mapped_column(
        String(256), nullable=True,
        comment="Extracted product or company name (if applicable)."
    )
    category: Mapped[str] = mapped_column(
        String(64), nullable=False,
        comment="Classifier-assigned signal category."
    )
    evidence_quote: Mapped[Optional[str]] = mapped_column(
        Text, nullable=True,
        comment="Key verbatim quote from the source that supports the classification."
    )
    confidence: Mapped[float] = mapped_column(
        Float, nullable=False,
        comment="Classifier confidence in the range [0.0, 1.0]."
    )
    trend_signal_present: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False,
        comment="True if the classifier determined a trend signal is present."
    )
    raw_model_output: Mapped[str] = mapped_column(
        Text, nullable=False,
        comment="Always log full LLM response — critical for debugging hallucinations."
    )
    model_version: Mapped[str] = mapped_column(
        String(128), nullable=False,
        comment="Model identifier used for this classification (e.g. 'gpt-4o-mini')."
    )
    classified_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, default=_utcnow,
        comment="UTC timestamp when the classification was produced."
    )
    passed_validation: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False,
        comment="True if the output passed the hallucination / schema validation check."
    )
    prompt_version: Mapped[Optional[str]] = mapped_column(
        String(64), nullable=True,
        comment="Version of the system prompt used."
    )
    prompt_tokens: Mapped[Optional[int]] = mapped_column(
        Integer, nullable=True,
        comment="Number of prompt tokens used."
    )
    completion_tokens: Mapped[Optional[int]] = mapped_column(
        Integer, nullable=True,
        comment="Number of completion tokens used."
    )

    # Relationships
    cluster: Mapped["UniqueCluster"] = relationship(
        "UniqueCluster", back_populates="classifications"
    )


class AlertSent(Base):
    """Audit log of every Telegram alert that has been dispatched."""

    __tablename__ = "alerts_sent"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=_new_uuid, comment="UUID4 PK"
    )
    cluster_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("unique_clusters.id", ondelete="CASCADE"),
        nullable=False,
        comment="FK to the cluster that triggered this alert."
    )
    sent_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, default=_utcnow,
        comment="UTC timestamp when the alert was dispatched."
    )
    telegram_message_id: Mapped[Optional[int]] = mapped_column(
        Integer, nullable=True,
        comment="Telegram message ID returned by the Bot API (for future edits/deletes)."
    )
    alert_type: Mapped[str] = mapped_column(
        String(32), nullable=False,
        comment="Alert category label (e.g. 'new_signal', 'corroboration', 'digest')."
    )

    # Relationships
    cluster: Mapped["UniqueCluster"] = relationship(
        "UniqueCluster", back_populates="alerts_sent"
    )


class SourceHealth(Base):
    """Tracks ingestion health metrics for each data source."""

    __tablename__ = "source_health"

    __table_args__ = (
        Index("ix_source_health_source_name", "source_name", unique=True),
    )

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=_new_uuid, comment="UUID4 PK"
    )
    source_name: Mapped[str] = mapped_column(
        String(64), nullable=False, unique=True,
        comment="Canonical identifier for the data source (e.g. 'reddit_r_MachineLearning')."
    )
    last_success: Mapped[Optional[datetime]] = mapped_column(
        DateTime, nullable=True,
        comment="UTC timestamp of the most recent successful fetch."
    )
    consecutive_failures: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0,
        comment="Number of consecutive fetch failures since the last success."
    )
    total_items_24h: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0,
        comment="Total items ingested in the rolling 24-hour window."
    )
    is_degraded: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False,
        comment="True when the source is considered unhealthy."
    )
    quota_exhausted: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False,
        comment="True when the source API quota limits have been exhausted."
    )
    last_degradation_alert: Mapped[Optional[datetime]] = mapped_column(
        DateTime, nullable=True,
        comment="UTC timestamp of the last degradation alert sent to operators."
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, default=_utcnow, onupdate=_utcnow,
        comment="UTC timestamp of the last update to this row."
    )


class HallucinationReject(Base):
    """Logs classifications that repeatedly failed evidence validation."""

    __tablename__ = "hallucination_rejects"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=_new_uuid, comment="UUID4 PK"
    )
    cluster_id: Mapped[str] = mapped_column(
        String(36), nullable=False, comment="ID of the cluster that failed validation"
    )
    category: Mapped[str] = mapped_column(
        String(64), nullable=False
    )
    evidence_quote: Mapped[Optional[str]] = mapped_column(
        Text, nullable=True
    )
    confidence: Mapped[float] = mapped_column(
        Float, nullable=False
    )
    raw_model_output: Mapped[str] = mapped_column(
        Text, nullable=False
    )
    model_version: Mapped[str] = mapped_column(
        String(128), nullable=False
    )
    rejected_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, default=_utcnow
    )
    failure_reason: Mapped[str] = mapped_column(
        Text, nullable=False
    )


class DeadLetterAlert(Base):
    """Stores alerts that failed delivery to Telegram repeatedly."""

    __tablename__ = "dead_letter_alerts"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=_new_uuid, comment="UUID4 PK"
    )
    cluster_id: Mapped[str] = mapped_column(
        String(36), nullable=False
    )
    alert_type: Mapped[str] = mapped_column(
        String(32), nullable=False
    )
    message_payload: Mapped[str] = mapped_column(
        Text, nullable=False
    )
    failed_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, default=_utcnow
    )
    failure_reason: Mapped[str] = mapped_column(
        Text, nullable=False
    )



# ---------------------------------------------------------------------------
# Engine & session factory
# ---------------------------------------------------------------------------

engine = create_async_engine(
    settings.DATABASE_URL,
    echo=False,
    pool_pre_ping=True,
    future=True,
)

AsyncSessionLocal: async_sessionmaker[AsyncSession] = async_sessionmaker(
    bind=engine,
    expire_on_commit=False,
    class_=AsyncSession,
)


# ---------------------------------------------------------------------------
# Session context manager
# ---------------------------------------------------------------------------

@asynccontextmanager
async def get_session():  # type: ignore[return]
    """Yield an ``AsyncSession`` and automatically close it afterwards.

    Usage::

        async with get_session() as session:
            result = await session.execute(select(RawItem))
    """
    async with AsyncSessionLocal() as session:
        try:
            yield session
        except Exception:
            await session.rollback()
            raise
        finally:
            await session.close()


# ---------------------------------------------------------------------------
# Schema initialisation
# ---------------------------------------------------------------------------

async def init_db() -> None:
    """Create all tables that do not yet exist.

    Safe to call on every startup — SQLAlchemy uses ``CREATE TABLE IF NOT
    EXISTS`` semantics under the hood via ``checkfirst=True``.
    """
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
